# Generated by Django 5.1.1 on 2024-10-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0002_remove_user_username_user_is_admin_user_is_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
