# Generated by Django 5.1.1 on 2024-10-19 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 0, 26, 42, 751361, tzinfo=datetime.timezone.utc)),
        ),
    ]
