# Generated by Django 5.1.1 on 2024-10-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0004_user_company_user_is_company_admin'),
        ('StoreHouse', '0002_company_item_company_warehouse_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='StoreHouse.company'),
            preserve_default=False,
        ),
    ]
