# Generated by Django 5.1.1 on 2024-10-03 17:53

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0005_alter_user_company'),
        ('StoreHouse', '0002_company_item_company_warehouse_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 10, 10, 17, 53, 29, 481574, tzinfo=datetime.timezone.utc))),
                ('role', models.CharField(choices=[('admin', 'Админ'), ('employee', 'Сотрудник')], max_length=50)),
                ('used', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='StoreHouse.company')),
            ],
        ),
    ]
