# Generated by Django 5.1.1 on 2024-10-06 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0011_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 15, 4, 35, 339406, tzinfo=datetime.timezone.utc)),
        ),
    ]
