# Generated by Django 5.1.1 on 2024-10-09 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0012_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 19, 57, 11, 382662, tzinfo=datetime.timezone.utc)),
        ),
    ]
