# Generated by Django 5.1.1 on 2024-10-10 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0015_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 6, 40, 20, 299247, tzinfo=datetime.timezone.utc)),
        ),
    ]
