# Generated by Django 5.1.1 on 2024-10-25 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0017_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 1, 14, 58, 30, 306334, tzinfo=datetime.timezone.utc)),
        ),
    ]
