# Generated by Django 5.1.1 on 2024-10-25 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0018_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 1, 15, 8, 49, 517222, tzinfo=datetime.timezone.utc)),
        ),
    ]
