# Generated by Django 5.1.1 on 2024-10-06 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0021_user_middle_name_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 21, 4, 57, 399686, tzinfo=datetime.timezone.utc)),
        ),
    ]
