# Generated by Django 5.1.1 on 2024-10-26 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0024_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 9, 48, 7, 67065, tzinfo=datetime.timezone.utc)),
        ),
    ]
