# Generated by Django 5.1.1 on 2024-10-10 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0025_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 14, 25, 6, 438069, tzinfo=datetime.timezone.utc)),
        ),
    ]
