# Generated by Django 5.1.1 on 2024-10-07 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0028_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 23, 49, 39, 866456, tzinfo=datetime.timezone.utc)),
        ),
    ]
