# Generated by Django 5.1.1 on 2024-10-08 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0038_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 0, 50, 16, 865003, tzinfo=datetime.timezone.utc)),
        ),
    ]
