# Generated by Django 5.1.1 on 2024-09-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='Не указано', max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(default='Не указано', max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('phone_number', models.CharField(default='Не указано', max_length=20, verbose_name='Номер телефона')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Роль')),
            ],
        ),
    ]
