# Generated by Django 5.1.1 on 2024-09-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес электронной почты'),
        ),
    ]
