# Generated by Django 5.1.1 on 2024-09-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_userprofilemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='role',
            field=models.CharField(default='employee', max_length=20, verbose_name='Роль'),
        ),
    ]
