# Generated by Django 5.1.1 on 2024-09-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_userprofilemodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='email',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='first_name',
            field=models.TextField(default='Не указано', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='last_name',
            field=models.TextField(default='Не указано', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='middle_name',
            field=models.TextField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone_number',
            field=models.TextField(default='Не указано', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='role',
            field=models.TextField(default='employee', max_length=20, verbose_name='Роль'),
        ),
    ]
