# Generated by Django 5.1.1 on 2024-09-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_userprofilemodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='password',
            field=models.TextField(default='Не указано', max_length=20, verbose_name='Пароль'),
        ),
    ]
