# Generated by Django 5.1.1 on 2024-10-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StoreHouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Не проведена'), ('completed', 'Проведена')], default='pending', max_length=10)),
                ('warehouses', models.ManyToManyField(to='StoreHouse.warehouse')),
            ],
        ),
    ]
