# Generated by Django 5.1.1 on 2024-10-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StoreHouse', '0004_remove_item_assigned_to_remove_item_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('warehouses', models.ManyToManyField(to='StoreHouse.warehouse')),
            ],
        ),
    ]
