# Generated by Django 5.1.1 on 2024-10-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryRequests', '0001_initial'),
        ('StoreHouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='extra_items',
            field=models.ManyToManyField(blank=True, related_name='extra_in_requests', to='StoreHouse.item'),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='items',
            field=models.ManyToManyField(related_name='requests', to='StoreHouse.item'),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='missing_items',
            field=models.ManyToManyField(blank=True, related_name='missing_in_requests', to='StoreHouse.item'),
        ),
    ]
