# Generated by Django 5.1.1 on 2024-10-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryRequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Не проведена'), ('completed', 'Проведена')], default='pending', max_length=10),
        ),
    ]
