# Generated by Django 5.1.1 on 2024-10-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryRequests', '0003_inventoryrequest_extra_items_inventoryrequest_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryrequest',
            old_name='warehouse',
            new_name='warehouses',
        ),
    ]
