# Generated by Django 5.1.1 on 2024-10-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryRequests', '0003_inventoryrequest_serial_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrequest',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='employee',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='serial_numbers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Не проведена'), ('completed', 'Проведена')], default='pending', max_length=10),
        ),
    ]
