# Generated by Django 5.1.1 on 2024-10-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryRequests', '0005_alter_inventoryrequest_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='serial_numbers',
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='employee',
            field=models.CharField(max_length=200),
        ),
    ]
