# Generated by Django 5.1.1 on 2024-10-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryRequests', '0006_remove_inventoryrequest_serial_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='serial_numbers',
            field=models.JSONField(default=list),
        ),
    ]
