# Generated by Django 5.1.1 on 2024-10-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryRequests', '0007_inventoryrequest_serial_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrequest',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
