# Generated by Django 5.1.1 on 2024-10-08 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryRequests', '0009_alter_inventoryrequest_serial_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='serial_numbers',
        ),
    ]
