# Generated by Django 5.1.1 on 2024-10-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreHouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='assigned_to',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='registration_date',
            field=models.DateField(null=True),
        ),
    ]
