# Generated by Django 5.1.1 on 2024-10-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreHouse', '0002_company_item_company_warehouse_company'),
        ('StoreHouse', '0002_item_assigned_to_item_location_and_more'),
    ]

    operations = [
    ]
