# Generated by Django 5.1.1 on 2024-10-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreHouse', '0003_merge_20241006_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='registration_date',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.CharField(blank=True, max_length=50, null=True)),
                ('row_number', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='StoreHouse.item')),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StoreHouse.warehouse')),
            ],
        ),
    ]
