# Generated by Django 5.1.1 on 2024-10-24 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreHouse', '0004_itemhistory_delete_itemmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhistory',
            name='action_type',
            field=models.CharField(choices=[('created', 'Создано'), ('updated', 'Изменено'), ('deleted', 'Удалено')], default='updated', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemhistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemhistory',
            name='field_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itemhistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreHouse.item'),
        ),
    ]
