# Generated by Django 5.1.1 on 2024-10-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreHouse', '0004_remove_item_assigned_to_remove_item_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='fullness',
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
