# Generated by Django 5.1.1 on 2024-10-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreHouse', '0004_remove_item_assigned_to_remove_item_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
