# Generated by Django 5.1.1 on 2024-10-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreHouse', '0005_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='StoreHouse.warehouse'),
        ),
    ]
