# Generated by Django 5.1.1 on 2024-10-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreHouse', '0005_itemhistory_action_type_alter_itemhistory_changed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='itemhistory',
            name='item',
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='item_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='responsible_employee_email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='responsible_employee_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='responsible_employee_surname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
