# Generated by Django 5.1.1 on 2024-10-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreHouse', '0006_remove_itemhistory_changed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhistory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='StoreHouse.company'),
            preserve_default=False,
        ),
    ]
