# Generated by Django 5.1.1 on 2024-10-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreHouse', '0007_itemhistory_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhistory',
            name='warehouse_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
